// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTRsauHyv8ercvMvZUbfxyEcThtxTJ-sA',
    appId: '1:728104648644:web:3ae007567543a0c1fbee91',
    messagingSenderId: '728104648644',
    projectId: 'kazevent-43ca4',
    authDomain: 'kazevent-43ca4.firebaseapp.com',
    storageBucket: 'kazevent-43ca4.appspot.com',
    measurementId: 'G-ET25YVZXFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoI2_l4wUnbgccJ3dCqiBuH7WAegWl9A4',
    appId: '1:728104648644:android:6a32279b5bb4508ffbee91',
    messagingSenderId: '728104648644',
    projectId: 'kazevent-43ca4',
    storageBucket: 'kazevent-43ca4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ0uLMWJuDTIO7Mlh6ZTj5BVsE6jMAcnw',
    appId: '1:728104648644:ios:2c88552bc821d61ffbee91',
    messagingSenderId: '728104648644',
    projectId: 'kazevent-43ca4',
    storageBucket: 'kazevent-43ca4.appspot.com',
    iosClientId: '728104648644-gnpj5tlk7h1i55l2n50lisru2d7f8boh.apps.googleusercontent.com',
    iosBundleId: 'com.example.kazEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ0uLMWJuDTIO7Mlh6ZTj5BVsE6jMAcnw',
    appId: '1:728104648644:ios:3f6e20ba7307dbd2fbee91',
    messagingSenderId: '728104648644',
    projectId: 'kazevent-43ca4',
    storageBucket: 'kazevent-43ca4.appspot.com',
    iosClientId: '728104648644-olqaccqejqn8j39h8vimdhp72verkjj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.kazEvents.RunnerTests',
  );
}
